import { loadConfig } from "../core/config.js";
import { getProfileDefinition } from "../core/profiles/definitions.js";
import type { CommandResult } from "../core/types.js";

export function runProjectStubCommand(repoRoot: string): CommandResult {
  const config = loadConfig(repoRoot);
  const profile = getProfileDefinition(config.profile.id);

  const prompt = `# Project-Specific Aiforge Customization Request

I already have the generic \`.cursor\` / \`.codex\` / \`.agent\` / \`.agents\` workflow baseline generated by \`aiforge\`.

Please analyze this project and produce only the project-specific additions I still need.

## Current project context

- Profile: \`${config.profile.id}\`
- Tracker: \`${config.workflow.tracker}\`
- Main branch: \`${config.project.mainBranch}\`
- Canonical tasks:
  - build: \`${config.task.command} ${config.task.tasks.build}\`
  - test: \`${config.task.command} ${config.task.tasks.test}\`
  - lint: \`${config.task.command} ${config.task.tasks.lint}\`
  - verify: \`${config.task.command} ${config.task.tasks.verify}\`
  - review: \`${config.task.command} ${config.task.tasks.review}\`

## Existing generic surfaces

- \`.cursor/HIERARCHY.md\`
- \`.ai/skills/*\`
- \`.ai/reference/*\`
- \`.ai/context/*\`
- \`.ai/linear-scope.json\`
- \`.ai/rules/*\`
- \`.cursor/skills -> .ai/skills\`
- \`.agent/skills -> .ai/skills\`
- \`.codex/skills -> .ai/skills\`
- \`.agents/skills -> .ai/skills\`
- \`.cursor/rules -> .ai/rules\`
- \`.cursor/reference -> .ai/reference\`
- \`.cursor/context -> .ai/context\`
- \`.cursor/hooks.json\`
- \`.cursor/hooks/*\`
- \`.codex/hooks/*\`
- \`AGENTS.md\`
- \`MANIFESTO.md\`
- \`Taskfile.yml\`

## What I need from you

1. Analyze the actual repository structure and stack specifics.
2. Generate only project-dependent additions or edits.
3. Keep generic process kernel unchanged unless there is a real conflict.
4. Do not rewrite the whole template pack.

## Fill or update these project-specific surfaces

- \`.ai/rules/project-profile.mdc\`
- \`MANIFESTO.md\`
- \`Taskfile.yml\`
- \`.ai/linear-scope.json\`
- \`.cursor/settings.json\`
- \`.cursor/mcp.example.json\`

## Add any missing project-specific rules if needed

Examples:

- architecture constraints specific to this repo
- stack-specific test/lint/build commands
- docker/container names
- package manager details
- module/layout conventions
- import-boundary rules
- docs sync rules
- MCP placeholders specific to the project

## Important constraints

- Keep commands executable as written.
- Prefer concise, enforceable rules over high-level prose.
- Do not duplicate generic workflow files if a small project override is enough.
- If something should stay manual, output an explicit TODO block.

## Output format

Return:

1. a short analysis of what is project-specific here
2. exact file patches or file contents to apply
3. a list of manual values I still need to fill myself

## Profile hints

${profile.notes.map((entry) => `- ${entry}`).join("\n")}
`;

  return {
    ok: true,
    code: 0,
    message: prompt
  };
}
